### ISSUE TITLE
fail for QT5.9

### ISSUE THREAD

**Issue by agwtpcbox** [IENT/YUView#113]
can the YUView support QT5.9?

tCore -Ibuild/release/.moc -isystem /usr/include/libdrm -Ibuild/release/.ui -I../../../Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++ -o build/release/.obj/mainwindow.o source/mainwindow.cpp
source/mainwindow.cpp: In member function ‘void MainWindow::createMenusAndActions()’:
source/mainwindow.cpp:160:89: error: no matching function for call to ‘MainWindow::connect(QPointer<QAction>&, void (QAction::*)(bool), MainWindow* const, void (MainWindow::*)())’
     connect(recentFileActions[i], &QAction::triggered, this, &MainWindow::openRecentFile);

**Comment by ChristianFeldmann** [comment]
I am successfully building YUView with Qt 5.9.2 on Windows so yes YUView should build with Qt 5.9. Could you please provide more information on what your exact configuration is? 

- What platform are you on? 
- How did you obtain Qt? 
- Which branch of YUView did you use? If you used the master branch could you also test and see if the development branch has the same problem?

**Comment by ChristianFeldmann** [comment]
Ok I can't reproduce this without more information. Please reopen if you have more information.
