### ISSUE TITLE
2.2 Release fails to compile on Ubunutu 16.04

### ISSUE THREAD

**Issue by arndtc** [IENT/YUView#169]
I'm able to build the YUView 2.1 sources, but when I try to build with the YUView 2.2 sources I get the following error:
`qmake`
`make`

`source/parserCommon.cpp: In member function ‘unsigned int parserCommon::sub_byte_reader::readBits(int, QString&)’:
source/parserCommon.cpp:80:48: error: ‘assert’ was not declared in this scope
       assert(nrBits < 8 && nrBits < curBitsLeft);
                                                ^
source/parserCommon.cpp: In member function ‘void parserCommon::sub_byte_writer::writeData(QByteArray)’:
source/parserCommon.cpp:405:24: error: ‘assert’ was not declared in this scope
   assert(posInByte == 7);
                        ^
source/parserCommon.cpp: In member function ‘void parserCommon::reader_helper::addLogSubLevel(QString)’:
source/parserCommon.cpp:438:25: error: ‘assert’ was not declared in this scope
   assert(!name.isEmpty());
                         ^
source/parserCommon.cpp: In member function ‘bool parserCommon::reader_helper::readBits(int, QByteArray&, QString, int)’:
source/parserCommon.cpp:535:22: error: ‘assert’ was not declared in this scope
   assert(numBits <= 8);
                      ^
Makefile:1737: recipe for target 'build/release/.obj/parserCommon.o' failed
make: *** [build/release/.obj/parserCommon.o] Error 1`

**Comment by nolyn** [comment]
I created the branch development_fix_ubutnu16_04_includes, directly from master, can you try it? it works on my Ubuntu 16.04. Some includes were missing.

**Comment by zmcui** [comment]
> I created the branch development_fix_ubutnu16_04_includes, directly from master, can you try it? it works on my Ubuntu 16.04. Some includes were missing.

it works for me on ubuntu 18.04, thanks

**Comment by ChristianFeldmann** [comment]
I corrected the includes also in the development branch.
I also added codeship to our build pipeline so that we can spot compilation errors on ubuntu 16.04 and 18.04 and the stock packages there: https://github.com/IENT/YUView/pull/172

**Comment by ChristianFeldmann** [comment]
So this will be fixed with the next release to master. Which we should do soon. I will close this for now.

**Comment by arndtc** [comment]
Thanks.  I confirmed that this solved the build issue on Ubuntu 16.04.
